
--학과정보
SELECT * FROM DEPARTMENT;
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;


SELECT S.NAME, S.DEPTNO1, D.DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO;


SELECT *
FROM STUDENT S, PROFESSOR P, DEPARTMENT D
WHERE S.PROFNO = P.PROFNO
AND S.DEPTNO1 = D.DEPTNO;

SELECT *
FROM 
STUDENT S INNER JOIN PROFESSOR P 
ON S.PROFNO = P.PROFNO
INNER JOIN DEPARTMENT D 
ON S.DEPTNO1 = D.DEPTNO;



SELECT *
FROM STUDENT S, PROFESSOR P, DEPARTMENT D
WHERE S.PROFNO = P.PROFNO
AND S.DEPTNO1 = D.DEPTNO
AND S.DEPTNO1 = 101;

--------------------------------------------------

1) 학생명, 학생학과번호, 학생의 학과명, 교수명, 교수학과번호
SELECT S.NAME, S.DEPTNO1, D.DNAME, P.NAME, P.DEPTNO
FROM STUDENT S, DEPARTMENT D, PROFESSOR P
WHERE S.DEPTNO1 = D.DEPTNO
AND S.PROFNO = P.PROFNO;

2) 학생명, 학생학과번호, 교수의 학과명, 교수명, 교수학과번호
SELECT S.NAME, S.DEPTNO1, D.DNAME, P.NAME, P.DEPTNO
FROM STUDENT S, PROFESSOR P, DEPARTMENT D
WHERE S.PROFNO = P.PROFNO
AND P.DEPTNO = D.DEPTNO;

3) 학생명, 학생학과번호, 학생의 학과명, 교수명, 교수학과번호, 교수의 학과명

SELECT S.NAME, S.DEPTNO1, DS.DNAME, P.NAME, P.DEPTNO, DP.DNAME
FROM STUDENT S, DEPARTMENT DS, PROFESSOR P, DEPARTMENT DP
WHERE S.PROFNO = P.PROFNO   -- 학생 <--> 지도교수 (PROFNO 기준)
AND S.DEPTNO1 = DS.DEPTNO   -- 학생 <--> 학과정보 (DEPTNO1 | DEPTNO)
AND P.DEPTNO = DP.DEPTNO;   -- 교수 <--> 학과정보 (DEPTNO 기준)


-----------------------------------------------------------
INNER JOIN
OUTER JOIN

등가조인    조인의 연결 조건 = 같다
비등가조인   조인의 연결 조건 = 같다가 아닌 다른 조건으로 연결


SELECT * FROM CUSTOMER;
SELECT * FROM GIFT;

POINT 점수 G_START ~ G_END 사이에 들어가면 해당 사은품 수령

SELECT *
FROM CUSTOMER C, GIFT G
WHERE C.POINT BETWEEN G.G_START AND G.G_END;


SELF JOIN


SELECT * FROM EMP;

SELECT *
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;


SELECT A.EMPNO, A.NAME, A.PEMPNO, B.EMPNO, B.NAME
FROM EMP2 A, EMP2 B
WHERE A.PEMPNO = B.EMPNO;