/*----------------------------------------*/
기타 복수행 함수

집계

--EMP 부서와 직업별 평균 급여와 사원수

SELECT DEPTNO, JOB, AVG(SAL) 평균급여, COUNT(*) 사원수
FROM EMP
GROUP BY DEPTNO, JOB;

--EMP 부서별 평균 급여와 사원수
SELECT DEPTNO, AVG(SAL) 평균급여, COUNT(*) 사원수
FROM EMP
GROUP BY DEPTNO;

--EMP 전체 사원의 평균 급여와 사원수
SELECT AVG(SAL), COUNT(*)
FROM EMP;

--위 3개의 집계 내역을 하나로 통함

SELECT DEPTNO, JOB, AVG(SAL) 평균급여, COUNT(*) 사원수
FROM EMP
GROUP BY DEPTNO, JOB
UNION ALL
SELECT DEPTNO, NULL, AVG(SAL), COUNT(*)
FROM EMP
GROUP BY DEPTNO
UNION ALL
SELECT NULL, NULL, AVG(SAL), COUNT(*)
FROM EMP
ORDER BY DEPTNO, 2;


*** ROLLUP

SELECT DEPTNO, JOB, AVG(SAL) 평균급여, COUNT(*) 사원수
FROM EMP
--GROUP BY ROLLUP(JOB, DEPTNO);
GROUP BY ROLLUP(DEPTNO, JOB);
--GROUP BY ROLLUP((DEPTNO, JOB));

GROUP BY ROLLUP(DEPTNO, JOB)
1) GROUP BY DEPTNO, JOB 그룹화 데이터 집계
2) GROUP BY DEPTNO 그룹화 데이터 집계
3) () 그룹화 데이터 집계 -> 전체집계

GROUP BY ROLLUP(JOB, DEPTNO)
1) GROUP BY JOB, DEPTNO 그룹화 데이터 집계
2) GROUP BY JOB 그룹화 데이터 집계
3) () 그룹화 데이터 집계 -> 전체집계

GROUP BY ROLLUP((DEPTNO, JOB))
1) GROUP BY (DEPTNO, JOB) 그룹화 데이터 집계
2) () 그룹화 데이터 집계 -> 전체집계



GROUP BY ROLLUP(EMPNO, DEPTNO, JOB)
1) EMPNO, DEPTNO, JOB
2) EMPNO, DEPTNO
3) EMPNO
4) ()

GROUP BY ROLLUP(EMPNO, (DEPTNO, JOB))
1) EMPNO, (DEPTNO, JOB)
2) EMPNO
3) ()


SELECT DEPTNO, JOB, AVG(SAL) 평균급여, COUNT(*) 사원수
FROM EMP
GROUP BY CUBE(DEPTNO, JOB);

ROLLUP
1) DEPTNO, JOB
2) DEPTNO
3) ()

CUBE
1) DEPTNO, JOB
2) DEPTNO
3)         JOB
4) ()


/*----------------------------------------*/

순위 RANK() OVER (ORDER BY 정렬기준대상)
그룹단위 순위 RANK() OVER (PARTITION BY 그룹기준 ORDER BY 정렬기준대상)

SELECT
    ENAME,
    SAL
FROM EMP
ORDER BY SAL;

SELECT
    ENAME,
    SAL,
    RANK() OVER (ORDER BY SAL) 낮은급여순위,
    RANK() OVER (ORDER BY SAL DESC) 높은급여순위,
    DENSE_RANK() OVER (ORDER BY SAL DESC) 높은급여순위
FROM EMP;

SELECT
    NAME,
    HEIGHT,
    RANK() OVER (ORDER BY HEIGHT DESC) 키순위,
    DENSE_RANK() OVER (ORDER BY HEIGHT DESC) 키순위,
    GRADE,
    HEIGHT,
    RANK() OVER (PARTITION BY GRADE ORDER BY HEIGHT DESC) 학년별키순위,
    DENSE_RANK() OVER (PARTITION BY GRADE ORDER BY HEIGHT DESC) 학년별키순위
FROM STUDENT
ORDER BY GRADE;