-- 1.
SELECT
    NAME,JUMIN,BIRTHDAY,
    CEIL(TO_NUMBER(TO_CHAR(BIRTHDAY,'MM'))/3) || '분기' 분기
FROM STUDENT;

-- 2.
SELECT
    EMPNO,ENAME,SAL,
    CASE
        WHEN SAL BETWEEN 1 AND 1000 THEN 'Level 1'
        WHEN SAL BETWEEN 1001 AND 2000 THEN 'Level 2'
        WHEN SAL BETWEEN 2001 AND 3000 THEN 'Level 3'
        WHEN SAL BETWEEN 3001 AND 4000 THEN 'Level 4'
        WHEN SAL > 0 THEN 'Level 5'
    END 급여등급
FROM EMP;
        